import { useEffect, useState } from "react"; import { Link, useRoute } from "wouter"; import { useQuery } from "@tanstack/react-query";
import Header from "@/components/Header"; import Footer from "@/components/Footer"; import { useShopifyCart } from "@/components/ShopifyCart";
import { usePageSEO } from "@/hooks/usePageSEO"; import { ecoTrack } from "@/lib/analytics"; import { formatMoney, productPriceLabel, variantRequiresSelection } from "@/lib/shopify-ui"; import type { ShopifyProduct } from "@shared/shopify";
async function loadProduct(handle: string): Promise<ShopifyProduct> { const response = await fetch(`/api/shopify/products/${encodeURIComponent(handle)}`); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load this product."); return data; }
export default function ShopifyProductPage() {
  const [, params] = useRoute<{ handle: string }>("/products/:handle"); const handle = params?.handle || ""; const query = useQuery({ queryKey: ["shopify-product", handle], queryFn: () => loadProduct(handle), enabled: !!handle, retry: 1 });
  const [variantId, setVariantId] = useState(""); const cart = useShopifyCart(); const product = query.data; const available = product?.variants.filter(v => v.availableForSale) || [];
  useEffect(() => { if (!product) return; setVariantId(variantRequiresSelection(product.variants) ? "" : available[0]?.id || ""); ecoTrack("view_item", { item_id: product.id, item_name: product.title, value: Number(product.price.amount), currency: product.price.currencyCode }); }, [product?.id]);
  usePageSEO({ title: product ? `${product.title} | EcoShopGuide` : "Wedding Product | EcoShopGuide", description: product?.description || "Shop the Wedding collection.", canonical: `https://ecoshopguide.com/products/${handle}` });
  const selected = product?.variants.find(v => v.id === variantId);
  return <div className="min-h-screen flex flex-col bg-[#f7f4ee] text-[#1f2a24]"><Header/><main className="flex-1 max-w-6xl w-full mx-auto px-4 py-8 md:py-14"><Link href="/shop-the-look/weddings" className="text-sm underline">← Wedding collection</Link>
  {query.isPending && <p role="status" className="py-20 text-center">Loading product…</p>}{query.isError && <div role="alert" className="py-20 text-center"><p>This Wedding product is unavailable or couldn’t be loaded.</p><button className="underline mt-3" onClick={() => query.refetch()}>Try again</button></div>}
  {product && <div className="grid md:grid-cols-2 gap-8 md:gap-14 mt-6" data-shopify-product-id={product.id}><div className="bg-[#e8ddc9] aspect-[4/5]"><img className="w-full h-full object-cover" src={selected?.image?.url || product.featuredImage?.url || "/placeholder-product.svg"} alt={selected?.image?.altText || product.featuredImage?.altText || product.title}/></div><section><p className="text-xs uppercase tracking-[.2em] text-[#c65f3e]">Wedding collection</p><h1 className="font-serif text-3xl md:text-5xl mt-2 leading-tight">{product.title}</h1><p className="text-xl mt-4">{selected ? formatMoney(selected.price) : productPriceLabel(product.price, product.variants)}</p>{product.review && <p className="mt-2" aria-label={`${product.review.rating} out of 5 stars from ${product.review.count} reviews`}>★ {product.review.rating.toFixed(1)} · {product.review.count} reviews</p>}<p className="mt-6 leading-relaxed text-muted-foreground whitespace-pre-line">{product.description}</p>
  {product.variants.length > 1 && <fieldset className="mt-7"><legend className="font-semibold mb-3">Choose an option</legend><div className="grid gap-2 max-h-80 overflow-y-auto pr-1">{product.variants.map(v => <label key={v.id} data-shopify-variant-id={v.id} className={`border p-3 rounded flex gap-3 ${!v.availableForSale ? "opacity-50" : "cursor-pointer"}`}><input type="radio" name="variant" value={v.id} checked={variantId === v.id} onChange={() => setVariantId(v.id)} disabled={!v.availableForSale}/><span>{v.title}{!v.availableForSale && " - unavailable"} · {formatMoney(v.price)}</span></label>)}</div></fieldset>}
  <button disabled={!product.availableForSale || !selected || cart.loading} onClick={() => { if (selected) void cart.add(selected, product); }} className="mt-7 w-full rounded-full bg-[#294b3a] text-white py-4 font-semibold disabled:opacity-50">{!product.availableForSale ? "Currently unavailable" : !selected ? "Select an option" : cart.loading ? "Adding…" : "Add to cart"}</button>{cart.error && <p role="alert" className="mt-3 text-red-700">{cart.error}</p>}<p className="mt-3 text-xs text-muted-foreground">Checkout is completed securely on Shopify.</p></section></div>}
  </main><Footer showAffiliateDisclosure={false}/></div>;
}
