import { useEffect, useState } from "react"; import { Link, useRoute } from "wouter"; import { useQuery } from "@tanstack/react-query";
import Header from "@/components/Header"; import Footer from "@/components/Footer"; import { useShopifyCart } from "@/components/ShopifyCart"; import { MapPin, ShieldCheck, Truck } from "lucide-react";
import { usePageSEO } from "@/hooks/usePageSEO"; import { ecoTrack } from "@/lib/analytics"; import { formatMoney, productPriceLabel } from "@/lib/shopify-ui"; import { isSupportedCollectionHandle, type ShopifyProduct, type SupportedCollectionHandle } from "@shared/shopify";
async function loadProduct(handle: string): Promise<ShopifyProduct> { const response = await fetch(`/api/shopify/products/${encodeURIComponent(handle)}`); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load this product."); return data; }
export default function ShopifyProductPage() {
  const [, params] = useRoute<{ handle: string }>("/products/:handle"); const handle = params?.handle || ""; const query = useQuery({ queryKey: ["shopify-product", handle], queryFn: () => loadProduct(handle), enabled: !!handle, retry: 1 });
  const [variantId, setVariantId] = useState(""); const cart = useShopifyCart(); const product = query.data; const available = product?.variants.filter(v => v.availableForSale) || [];
  const collectionParam = typeof window === "undefined" ? null : new URLSearchParams(window.location.search).get("collection");
  const collection = collectionParam && isSupportedCollectionHandle(collectionParam) ? collectionParam : undefined as SupportedCollectionHandle | undefined;
  const collectionLabel = collection === "fall-halloween" ? "Fall & Halloween" : collection === "dorm" ? "Dorm" : collection === "wedding" ? "Wedding" : "Shop";
  const collectionHref = collection === "fall-halloween" ? "/shop-the-look/fall-halloween" : collection === "dorm" ? "/shop-the-look/dorm" : collection === "wedding" ? "/shop-the-look/weddings" : "/shop-the-look";
  useEffect(() => { if (!product) return; setVariantId(available[0]?.id || ""); ecoTrack("view_item", { item_id: product.id, item_name: product.title, value: Number(product.price.amount), currency: product.price.currencyCode, ...(collection ? { collection } : {}) }); }, [product?.id, collection]);
  usePageSEO({ title: product ? `${product.title} | Bambana` : "Product | Bambana", description: product?.description || "Shop the Bambana collection.", canonical: `https://www.shopbambana.com/products/${handle}` });
  const selected = product?.variants.find(v => v.id === variantId);
  return <div className="min-h-screen flex flex-col bg-[#f7f4ee] text-[#1f2a24]"><Header/><main className="flex-1 max-w-6xl w-full mx-auto px-4 py-8 md:py-14"><Link href={collectionHref} className="text-sm underline">← {collectionLabel} collection</Link>
  {query.isPending && <p role="status" className="py-20 text-center">Loading product…</p>}{query.isError && <div role="alert" className="py-20 text-center"><p>This product is unavailable or couldn’t be loaded.</p><button className="underline mt-3" onClick={() => query.refetch()}>Try again</button></div>}
  {product && <div className="grid md:grid-cols-2 gap-8 md:gap-14 mt-6" data-shopify-product-id={product.id}><div className="bg-[#e8ddc9] aspect-[4/5]"><img className="w-full h-full object-cover" src={selected?.image?.url || product.featuredImage?.url || "/placeholder-product.svg"} alt={selected?.image?.altText || product.featuredImage?.altText || product.title}/></div><section><p className="text-xs uppercase tracking-[.2em] text-[#c65f3e]">{collectionLabel} collection</p><h1 className="font-serif text-3xl md:text-5xl mt-2 leading-tight">{product.title}</h1>{product.review && <div className="mt-3"><p className="flex items-center gap-2 text-sm font-medium" aria-label={`${product.review.rating} out of 5 stars from ${product.review.count} reviews`}><span className="tracking-[.1em]" aria-hidden="true">{Array.from({ length: 5 }, (_, index) => <span key={index} className={index < Math.round(product.review!.rating) ? "text-[#c65f3e]" : "text-[#d9d3c8]"}>★</span>)}</span><span>{product.review.rating.toFixed(1)} ({product.review.count} reviews)</span></p><p className="mt-1 text-xs text-muted-foreground">Supplier reviews via Shopify Collective</p></div>}<p className="text-xl mt-4">{selected ? formatMoney(selected.price) : productPriceLabel(product.price, product.variants)}</p><p className="mt-6 leading-relaxed text-muted-foreground whitespace-pre-line">{product.description}</p>
  {available.length > 1 && <fieldset className="mt-7"><legend className="font-semibold mb-3">Choose an option</legend><div className="grid gap-2 max-h-80 overflow-y-auto pr-1">{available.map(v => <label key={v.id} data-shopify-variant-id={v.id} className="border p-3 rounded flex gap-3 cursor-pointer"><input type="radio" name="variant" value={v.id} checked={variantId === v.id} onChange={() => setVariantId(v.id)}/><span>{v.title} · {formatMoney(v.price)}</span></label>)}</div></fieldset>}
  <button disabled={!product.availableForSale || !selected || cart.loading} onClick={() => { if (selected) void cart.add(selected, { id: product.id, title: product.title, collection }); }} className="mt-7 w-full rounded-full bg-[#294b3a] text-white py-4 font-semibold disabled:opacity-50">{!product.availableForSale ? "Currently unavailable" : !selected ? "Select an option" : cart.loading ? "Adding…" : "Add to cart"}</button>{cart.error && <p role="alert" className="mt-3 text-red-700">{cart.error}</p>}<div className="mt-5 grid gap-3 border-t pt-5 text-sm">{product.supplierShipsInDays && <div className="flex gap-3"><Truck className="mt-0.5 h-4 w-4 shrink-0 text-[#294b3a]" aria-hidden="true"/><p><span className="font-semibold">Typically ships in {product.supplierShipsInDays} days.</span> Supplier-provided timing via Shopify Collective.</p></div>}<div className="flex gap-3"><MapPin className="mt-0.5 h-4 w-4 shrink-0 text-[#294b3a]" aria-hidden="true"/><p><span className="font-semibold">Delivery estimate at checkout.</span> Shipping options and the expected arrival window are confirmed for your address.</p></div><div className="flex gap-3"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-[#294b3a]" aria-hidden="true"/><p><span className="font-semibold">Secure Shopify checkout.</span> Inventory is checked live before your order is placed.</p></div></div></section></div>}
  </main><Footer showAffiliateDisclosure={false}/></div>;
}
