// AUTO-GENERATED by scripts/fetchProducts.mjs — do not edit by hand.
// Live product data (image, price, rating, reviews) keyed by product id.
// Run: node scripts/fetchProducts.mjs
export interface FetchedProduct {
  image?: string;
  price?: string;
  listPrice?: string;
  rating?: number;
  reviewCount?: number;
  retailer?: string;
  title?: string;
}

export const PRODUCT_DATA: Record<string, FetchedProduct> = {
  "green-ess-001": {"retailer":"DHgate","price":"$18.04","rating":5,"reviewCount":529,"title":"Climbing Plants Supports Retractable Moss Pole... From Dh4402004, &Price; | DHgate.Com","image":"/products/green-ess-001.jpg"},
};
